version: '3.4'

services:
  blazorempty:
    image: ${DOCKER_REGISTRY-}blazorempty
    build:
      context: .
      dockerfile: BlazorEmpty/Dockerfile
    ports:
      - "5000:80"
    networks:
      - postgres
    volumes:
    - blazorempty:/var/lib/blazorempty
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Kot_Kuzma1}
      POSGRES_DB: "66bitFootballer"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres
  pgagmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    blazorempty:
